repos:
  - repo: https://github.com/psf/black        # Formatter
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8     # Linter
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort      # Tri des imports
    rev: 5.13.2
    hooks:
      - id: isort
